[package]
name = "fury-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "=0.46.0", default-features = false, features = ["macros", "realloc"] }
dlmalloc = { version = "0.2", features = ["global"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(verus_keep_ghost)'] }
