[package]
name = "game-client-networking"
edition = "2024"
version = "0.1.0"

[features]
web = []

[dependencies]
game-client-models = { path = "../models" }
game-core = { path = "../../core" }
spacetimedb-sdk = "=2.2.0"
bevy = { version = "^0.18", default-features = false }
web-time = "1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
home = "0.5"

[target.wasm32-unknown-unknown.dependencies]
spacetimedb-sdk = { version = "=2.2.0", features = ["browser"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Location"] }

[lints]
workspace = true
