[package]
name = "game-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "=2.2.0"
game-core = { path = "../core" }
glam = { workspace = true }
avian3d = { path = "../crates/avian/crates/avian3d", default-features = false, features = ["3d", "f32", "parry-f32", "enhanced-determinism"] }

[lints]
workspace = true
